"""empty message

Revision ID: 1cc6bbc105e4
Revises: 4f5395bf1228
Create Date: 2025-06-26 13:09:27.872799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cc6bbc105e4'
down_revision = '4f5395bf1228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_professional_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_professional_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by_professional_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['rejected_by_professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['approved_by_professional_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['requested_professional_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejected_by_professional_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_professional_id')
        batch_op.drop_column('requested_at')
        batch_op.drop_column('requested_professional_id')

    # ### end Alembic commands ###
