"""empty message

Revision ID: 4f5395bf1228
Revises: c38c6ddc7879
Create Date: 2025-06-24 15:07:15.138211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5395bf1228'
down_revision = 'c38c6ddc7879'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated_by_id',
                            sa.Integer(), nullable=True))
        batch_op.add_column(
            sa.Column('validated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(
            'fk_validated_by_id_users',  # ✅ Nombre agregado
            'users',
            ['validated_by_id'],
            ['id']
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('professional_student_data', schema=None) as batch_op:
        batch_op.drop_constraint(
            'fk_validated_by_id_users', type_='foreignkey')
        batch_op.drop_column('validated_at')
        batch_op.drop_column('validated_by_id')

    # ### end Alembic commands ###
