"""empty message

Revision ID: 80bb16305754
Revises: d666cc6a6b83
Create Date: 2025-07-03 17:13:04.073556

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '80bb16305754'
down_revision = 'd666cc6a6b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_file_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('medical_file_snapshot_medical_file_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'medical_file', ['medical_file_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('uploaded_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_file_snapshot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('medical_file_snapshot_medical_file_id_fkey', 'medical_file', ['medical_file_id'], ['id'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
