"""empty message

Revision ID: ae59547f4f0d
Revises: b6ca9b5fabb6
Create Date: 2025-07-02 20:14:57.632554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae59547f4f0d'
down_revision = 'b6ca9b5fabb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medical_file_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_file_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medical_file_id'], ['medical_file.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_file_snapshot')
    # ### end Alembic commands ###
