"""empty message

Revision ID: b6ca9b5fabb6
Revises: 5ed214bbec53
Create Date: 2025-06-29 20:24:30.308586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ca9b5fabb6'
down_revision = '5ed214bbec53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.alter_column('hypertension',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('diabetes',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('cancer',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('mental_illnesses',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('congenital_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('heart_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('liver_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('kidney_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('pathological_background', schema=None) as batch_op:
        batch_op.alter_column('visual_disability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('hearing_disability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('motor_disability',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('intellectual_disability',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pathological_background', schema=None) as batch_op:
        batch_op.alter_column('intellectual_disability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('motor_disability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hearing_disability',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('visual_disability',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('family_background', schema=None) as batch_op:
        batch_op.alter_column('kidney_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('liver_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('heart_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('congenital_diseases',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('mental_illnesses',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('cancer',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('diabetes',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('hypertension',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
