"""empty message

Revision ID: bdaa132466d4
Revises: 1cc6bbc105e4
Create Date: 2025-06-26 17:56:28.232300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdaa132466d4'
down_revision = '1cc6bbc105e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_file', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_requested_student_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('patient_requested_student_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['patient_requested_student_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medical_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('patient_requested_student_at')
        batch_op.drop_column('patient_requested_student_id')

    # ### end Alembic commands ###
